# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a7068d5c94961a4d5a540b78d3d0d3015dc981ef0dbf0a8713dd4edac1f7a6443a402e64acefb60f37afef5d74194c5664dcb760e52c8feaf2c077bfbb14493

test:
  secret_key_base: ac79062a73d1c13908807e0eb2c8fdd39b81c1ff583aebbcb60dab7b55b1044b98c3d632e90c943b568d66db1ac1494ce4f2628b0f2314a0e0150435c3796511

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
